name: Deploy Client Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trigger Vercel Redeployment
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            "${{ secrets.VERCEL_DEPLOY_HOOK }}"
