name: Deploy api Koyeb

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  redeploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Trigger Koyeb Redeployment
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
          KOYEB_SERVICE_ID: ${{ secrets.KOYEB_SERVICE_ID }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $KOYEB_API_TOKEN" \
            -H "Content-Type: application/json" \
            "https://app.koyeb.com/v1/services/${{ env.KOYEB_SERVICE_ID }}/redeploy" \
            -d '{}' # Cuerpo vacío para re-despliegue estándar (último commit, usa caché)
