name: Deploy client Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para 'git diff'

      - name: Check for 'client' changes and deploy
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          git diff --quiet HEAD^ HEAD -- ./client/
          DIFF_EXIT_CODE=$? # Almacenamos el código de salida de git diff

          if [ $DIFF_EXIT_CODE -ne 0 ]; then
            echo "Cambios detectados en 'client'. Intentando llamar al Deploy Hook de Vercel..."
            # Añadimos -v para modo verbose y --fail-with-body para ver errores HTTP
            curl -X POST -v --fail-with-body "$VERCEL_DEPLOY_HOOK"
            # $? aquí será el código de salida de curl
            if [ $? -eq 0 ]; then
              echo "Deploy Hook de Vercel llamado con éxito."
            else
              echo "ERROR: Fallo al llamar al Deploy Hook de Vercel. Revisa los logs de 'curl' arriba."
              exit 1 # Forzar la falla del paso si curl falla
            fi
          else
            echo "No hay cambios en 'client'. No se llama al Deploy Hook."
          fi
