name: Deploy client Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para 'git diff'

      - name: Check for 'client' changes and deploy
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run:
          | # Detecta si hay cambios en el subdirectorio client. 'git diff --quiet' devuelve 0 si NO hay cambios, 1 si SÍ los hay.
          git diff --quiet HEAD^ HEAD -- ./client/
          if [ $? -ne 0 ]; then
            echo "Cambios detectados en 'client'. Llamando al Deploy Hook de Vercel..."
            curl -X POST $VERCEL_DEPLOY_HOOK
            echo "Deploy Hook de Vercel llamado con éxito."
          else
            echo "No hay cambios en 'client'. No se llama al Deploy Hook."
          fi
